apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-app
  namespace: planning-app
  labels:
    app: planning-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: planning-app
  template:
    metadata:
      labels:
        app: planning-app
    spec:
      containers:
        - name: planning-app
          image: taakujobi/planning-app:6bca6d43af64d773996350133088f869a3756ff7
          ports:
            - containerPort: 80
