apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-app
  namespace: planning-app
  labels:
    app: planning-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: planning-app
  template:
    metadata:
      labels:
        app: planning-app
    spec:
      containers:
        - name: planning-app
          image: taakujobi/planning-app:6892e01f7d2d9f1a9ec22151d8322c97ee98e7de
          ports:
            - containerPort: 80
